name: Image Mirror

on:
  push:
    branches:
      - main

jobs:
  sync_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Skopeo and yq
        run: |
          sudo apt-get install -y skopeo
          sudo apt-get install -y yq

      - name: Login to GitHub Packages (GHCR)
        run: echo ${{ secrets.GITHUB_TOKEN }} | skopeo login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Pull and Push Images
        run: |
          # File containing list of images
          IMAGE_LIST="./infra-images.yaml"

          # Loop through each registry and image in the YAML file
          for registry in $(yq '. | keys | .[]' "${IMAGE_LIST}"); do

              # Loop through each image tag for this registry
              for image in $(yq ".${registry}[]" "${IMAGE_LIST}"); do

                  # Extract the image tag (e.g., nginx:1.0.0)
                  # and strip quotes
                  registry=$(echo "${registry}" | tr -d '"')
                  tag=$(echo "${image}" | cut -d':' -f2  | tr -d '"')
                  image_name=$(echo "${image}" | cut -d':' -f1 | tr -d '"')

                  # Construct the full source image path
                  SOURCE_IMAGE="docker://${registry}/${image_name}:${tag}"

                  # Define destination image on GHCR
                  GHCR_IMAGE="docker://ghcr.io/${{ github.repository_owner }}/infra/${image_name}:${tag}"

                  # Copy the image from the source registry to GitHub Packages (GHCR)
                  skopeo copy "${SOURCE_IMAGE}" "${GHCR_IMAGE}"
              done
          done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
